import { readFileSync } from "node:fs";
import { join } from "node:path";
import { resolveTopologyConfig } from "./resolver.js";
import type { Graph } from "./validate.js";

const TEMPLATE_FN: Record<string, string> = {
  diamond: "createDiamondWorkflow",
  "classify-and-act": "createClassifyWorkflow",
  "adversarial-verification": "createAdversarialWorkflow",
  "loop-until-done": "createLoopWorkflow",
  "generate-and-filter": "createGenerateFilterWorkflow",
  tournament: "createTournamentWorkflow",
  "memory-augmented": "createMemoryAugmentedWorkflow",
};

export function compileGraph(graph: Graph, templatesDir: string): string {
  const resolved = resolveTopologyConfig(graph.topology, graph.topology_config, templatesDir);

  // Collect the root template + every referenced subgraph template (deduped)
  const templateFiles = new Set<string>([`${graph.topology}.workflow.js`]);
  const collectSubgraphs = (obj: unknown) => {
    if (obj && typeof obj === "object") {
      for (const v of Object.values(obj as Record<string, unknown>)) {
        if (v && typeof v === "object" && "__subgraph" in v) {
          templateFiles.add(`${(v as { __subgraph: string }).__subgraph}.workflow.js`);
        }
        if (v && typeof v === "object") collectSubgraphs(v);
      }
    }
  };
  collectSubgraphs(resolved);

  // Inline all needed template sources (deduped, root last)
  const sources = [...templateFiles]
    .filter((f, i, arr) => arr.indexOf(f) === i)
    .map((f) => readFileSync(join(templatesDir, f), "utf-8"));
  const fnName = TEMPLATE_FN[graph.topology];

  const config = {
    metadata: graph.metadata,
    nodes: graph.nodes,
    limits: graph.limits,
    evidence: graph.evidence,
    topology_config: resolved,
    outputs: graph.outputs,
  };

  return [
    `// Generated by gk compile — DO NOT EDIT. Source of truth: graph.yaml`,
    `export const meta = ${JSON.stringify({ name: graph.metadata.name, description: graph.metadata.description ?? `${graph.topology} graph` }, null, 2)};`,
    ``,
    ...sources, // inlines root + all subgraph template definitions
    ``,
    `const graphConfig = ${JSON.stringify(config, null, 2)};`,
    ``,
    `export default ${fnName}(graphConfig);`,
  ].join("\n");
}
