// gk completions — static shell completion scripts generated from the command
// registry. The registry is already the single source of truth for help,
// did-you-mean, and the manifest; completions are just one more projection of
// it, so a new subcommand or flag becomes Tab-completable with no extra edit.
// Deliberately static (no dynamic completion): the CLI has no runtime-computed
// values worth completing yet.
import type { CAC } from "cac";
import { CLI_COMMANDS, subcommandsFor } from "../command-registry.js";
import { fail, ok } from "../output.js";

function words(): { topLevel: string[]; second: string[] } {
  const topLevel = [...new Set(CLI_COMMANDS.map((c) => c.path.split(" ")[0]))].sort();
  const second: Record<string, string[]> = {};
  for (const c of CLI_COMMANDS) {
    const parts = c.path.split(" ");
    if (parts.length === 2) {
      const group = second[parts[0]];
      if (group) group.push(parts[1]);
      else second[parts[0]] = [parts[1]];
    }
  }
  return { topLevel, second: Object.entries(second).map(([g, ws]) => `${g}:${ws.sort().join(" ")}`) };
}

function bashScript(): string {
  const { topLevel } = words();
  const groups = CLI_COMMANDS.map((c) => c.path.split(" ")[0]);
  const withSubs = [
    ...new Set(topLevel.filter((t) => groups.filter((g) => g === t).length > 0 && subcommandsFor(t) !== "")),
  ];
  return `# bash completion for gk — generated by \`gk completions bash\`
_gk_completions() {
  local cur="\${COMP_WORDS[COMP_CWORD]}"
  local prev="\${COMP_WORDS[COMP_CWORD-1]}"
  local sub=\${COMP_WORDS[1]}
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "${topLevel.join(" ")}" -- "$cur") )
    return 0
  fi
  case "$sub" in
${withSubs.map((t) => `    ${t}) COMPREPLY=( $(compgen -W "${subcommandsFor(t)}" -- "$cur") );;`).join("\n")}
  esac
  COMPREPLY=( $(compgen -W "${[...new Set(CLI_COMMANDS.flatMap((c) => c.options.map((o) => o.split(" ")[0])))].sort().join(" ")}" -- "$cur") )
  return 0
}
complete -F _gk_completions gk
`;
}

function zshScript(): string {
  const { topLevel } = words();
  const groups = [...new Set(CLI_COMMANDS.filter((c) => c.path.includes(" ")).map((c) => c.path.split(" ")[0]))];
  const allFlags = [...new Set(CLI_COMMANDS.flatMap((c) => c.options.map((o) => o.split(" ")[0])))].sort();
  return `#compdef gk
# zsh completion for gk — generated by \`gk completions zsh\`
_gk() {
  if (( CURRENT == 2 )); then
    compadd ${topLevel.join(" ")}
  fi
  case \${words[2]} in
${groups.map((g) => `    ${g}) compadd ${subcommandsFor(g).split(" ").sort().join(" ")};;`).join("\n")}
  esac
  compadd ${allFlags.join(" ")}
}
compdef _gk gk
`;
}

function fishScript(): string {
  const { topLevel } = words();
  const lines: string[] = [
    `# fish completion for gk — generated by \`gk completions fish\``,
    ...topLevel.map((t) => `complete -c gk -n '__fish_use_subcommand' -a '${t}' -d '${t}'`),
  ];
  for (const c of CLI_COMMANDS) {
    if (!c.path.includes(" ")) continue;
    const [g, leaf] = c.path.split(" ");
    lines.push(
      `complete -c gk -n '__fish_seen_subcommand_from ${g}' -a '${leaf}' -d '${c.description.split("\n")[0]}'`,
    );
  }
  const allFlags = [...new Set(CLI_COMMANDS.flatMap((c) => c.options.map((o) => o.split(" ")[0])))].sort();
  lines.push(...allFlags.map((f) => `complete -c gk -l '${f.replace(/^--/, "")}'`));
  return `${lines.join("\n")}\n`;
}

export function registerCompletionsCommand(cli: CAC) {
  cli
    .command("completions [shell]", "Print a shell completion script (bash | zsh | fish)")
    .example("$ gk completions zsh >> ~/.zshrc   # or: source <(gk completions zsh)")
    .option("--json", "JSON output")
    .action((shell: string | undefined, opts: { json?: boolean }) => {
      const scripts: Record<string, () => string> = { bash: bashScript, zsh: zshScript, fish: fishScript };
      const shellNames = Object.keys(scripts);
      if (!shell || !scripts[shell]) {
        console.log(
          JSON.stringify(
            fail("MISSING_ARG", `completions requires a shell: ${shellNames.join(" | ")}`, {
              available: shellNames,
              install: shellNames.map((s) => `source <(gk completions ${s})`),
            }),
          ),
        );
        return;
      }
      if (opts.json) {
        console.log(JSON.stringify(ok({ shell, script: scripts[shell]() })));
        return;
      }
      console.log(scripts[shell]());
    });
}
